# Basics of Linear Algebra: Vectors and Matrices
Linear algebra is a fundamental area of mathematics that is essential for understanding and effectively using machine learning libraries like PyTorch. In
this chapter, we will delve into the basics of linear algebra, focusing on vectors
and matrices, which are the building blocks for more complex operations and
algorithms.

A vector is a mathematical object that has both magnitude and direction. In a computational context, a vector can be thought of as an array of numbers. Formally, a vector in \$( \mathbb{R}^n \)$ is an ordered list of numbers, written as:

$
mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix}
$

Each element \$( v_i \)$ in the vector is a component of the vector. Vectors can represent various quantities such as position, velocity, or even data features.

In PyTorch, vectors can be represented using tensors. Below is an example of how to create a simple vector:


In [4]:
import torch
# Create a 3- dimensional vector
vector = torch.tensor([1 , 2, 3])
vector

tensor([1, 2, 3])

# Operations on Vectors

Vectors support a variety of operations, including addition, scalar multiplication, and the dot product. Here, we'll briefly discuss each operation:

## Addition

Vectors of the same dimension can be added together by adding the corresponding components. Given two vectors $\mathbf{a}$ and $\mathbf{b}$:

$$
\mathbf{c} = 
\begin{pmatrix}
a_1 + b_1 \\
a_2 + b_2 \\
\vdots \\
a_n + b_n
\end{pmatrix}
$$

In [6]:
a = torch.tensor([1 , 2, 3])
b = torch .tensor([4 , 5, 6])
c = a + b

c

tensor([5, 7, 9])

## Scalar Multiplication

A vector can be multiplied by a scalar (a single number), scaling each component of the vector:

$$
\mathbf{b} = c \mathbf{a} = 
\begin{pmatrix}
c \times a_1 \\
c \times a_2 \\
\vdots \\
c \times a_n
\end{pmatrix}
$$

Where:
- $c$ is the scalar
- $\mathbf{a}$ is the original vector
- $\mathbf{b}$ is the resulting scaled vector

In [7]:
c = 2
b = c * a
b

tensor([2, 4, 6])

## Dot Product

The dot product of two vectors of the same dimension is a scalar obtained by multiplying corresponding entries and summing the results:

$$
\mathbf{a} \cdot \mathbf{b} = a_1 \times b_1 + a_2 \times b_2 + \cdots + a_n \times b_n
$$

Alternatively, it can be written as:

$$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i
$$

Where:
- $\mathbf{a}$ and $\mathbf{b}$ are vectors of the same dimension
- $n$ is the dimension of the vectors
- $a_i$ and $b_i$ are the $i$-th components of vectors $\mathbf{a}$ and $\mathbf{b}$, respectively

In [16]:
print(f'{a=}')
print(f'{b=}')
dot_product = torch.dot(a, b)

dot_product

a=tensor([1, 2, 3])
b=tensor([2, 4, 6])


tensor(28)

In [10]:
from IPython.display import HTML
print('Recomndation: Video to explain vectors')

# Replace VIDEO_ID with the actual YouTube video ID
video_id = "VIDEO_ID"

youtube_html = f"""
<iframe width="560" height="315" src="https://www.youtube.com/embed/fNk_zzaMoSs?si=UcWFhCE182PijqLM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
"""

# Display the YouTube video
HTML(youtube_html)





Recomndation: Video to explain vectors


# Matrices

A matrix is a two-dimensional array of numbers arranged in rows and columns. It is often used to represent transformations and systems of linear equations. A matrix with $m$ rows and $n$ columns is called an $m \times n$ matrix, denoted as:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}
$$

Where:
- $a_{ij}$ represents the element in the $i$-th row and $j$-th column
- $m$ is the number of rows
- $n$ is the number of columns

In [18]:
# Create a 2x3 matrix
matrix = torch.tensor([[1 , 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

We can represent matrix in pure python or numpy, but we won;t get the magic of pytorch tensors

In [19]:
py_mat = [[1,2,3],[4,5,6]]
py_mat

[[1, 2, 3], [4, 5, 6]]

In [21]:
import numpy as np
np_mat =  np.array([[1,2,3],[4,5,6]])
np_mat

array([[1, 2, 3],
       [4, 5, 6]])

# Operations on Matrices

Matrices support operations such as addition, scalar multiplication, and matrix multiplication:

## Addition

Like vectors, matrices of the same dimensions can be added together. For two matrices $A$ and $B$ of dimensions $m \times n$, their sum $C = A + B$ is defined as:

$$
C = A + B = 
\begin{pmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}
\end{pmatrix}
$$

Where:
- $a_{ij}$ represents the element in the $i$-th row and $j$-th column of matrix $A$
- $b_{ij}$ represents the element in the $i$-th row and $j$-th column of matrix $B$
- $c_{ij} = a_{ij} + b_{ij}$ for all $i$ and $j$

In [22]:
A = torch.tensor([[1 , 2], [3, 4]])
B = torch.tensor([[5 , 6], [7, 8]])
C = A + B
# C is tensor ([[ 6, 8], [10 , 12]])
C

tensor([[ 6,  8],
        [10, 12]])

### Scalar Multiplication: 
Each element of a matrix is multiplied by a
scalar:

In [26]:
print(A)
D = 2 * A

D

tensor([[1, 2],
        [3, 4]])


tensor([[2, 4],
        [6, 8]])

### Matrix Multiplication

Two matrices can be multiplied if the number of columns in the first matrix equals the number of rows in the second matrix:

Let matrix \( A \) be of size \( m \times n \) and matrix \( B \) be of size \( n \times p \). The product \( C = A \times B \) will result in a matrix \( C \) of size \( m \times p \).

The element in row \( i \) and column \( j \) of matrix \( C \) is given by:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} \cdot B_{kj}
$$

Where:
- \( A_{ik} \) represents the element in row \( i \) and column \( k \) of matrix \( A \),
- \( B_{kj} \) represents the element in row \( k \) and column \( j \) of matrix \( B \),
- \( C_{ij} \) is the element in row \( i \) and column \( j \) of the resulting matrix \( C \).


In [30]:
E = torch.tensor([[1 , 2, 3], [4, 5, 6]])
F = torch.tensor([[7 , 8], [9, 10] , [11 , 12]])
print(f'{E=}\nshape={E.shape}\n')
print(f'{F=}\nshape={F.shape}\n')
G = E @ F
G

E=tensor([[1, 2, 3],
        [4, 5, 6]])
shape=torch.Size([2, 3])

F=tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
shape=torch.Size([3, 2])



tensor([[ 58,  64],
        [139, 154]])

### Practice Questions

- Create a vector with elements \([3, 5, 7]\) and perform scalar multiplication with 3. What is the resulting vector?

- Create two matrices \( X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \) and \( Y = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} \). 
  Perform the addition of \( X \) and \( Y \), and the scalar multiplication of \( X \) with 5.

- Calculate the dot product of vectors \([1, 4, 6]\) and \([2, 3, 5]\).

- Multiply matrices \( A = \begin{bmatrix} 2 & 4 \\ 1 & 3 \end{bmatrix} \) and \( B = \begin{bmatrix} 3 & 7 \\ 5 & 8 \end{bmatrix} \).


### Vector Spaces and Subspaces

Vectors and matrices are fundamental concepts in linear algebra and play a crucial role in machine learning frameworks like PyTorch. In this chapter, we will delve into the concepts of vector spaces and subspaces, which form the backbone for these mathematical entities.

A **vector space** is a collection of vectors that can be added together and multiplied by scalars (numbers) to produce another vector within the same space. In a more formal sense, a vector space over a field \( F \) is a set \( V \) along with two operations: vector addition and scalar multiplication, that satisfy the following axioms (rules):

#### Axioms of Vector Spaces:

- **Closure under Addition**: For any two vectors \( u, v \in V \), the sum \( u + v \) is also in \( V \).
- **Closure under Scalar Multiplication**: For any vector \( v \in V \) and scalar \( c \in F \), the product \( c \cdot v \) is in \( V \).
- **Associative and Commutative Properties**: Vector addition is both associative and commutative.
- **Additive Identity and Inverse**: There exists a zero vector \( 0 \) such that \( v + 0 = v \), and for every \( v \), there exists a vector \( -v \) such that \( v + (-v) = 0 \).
- **Distributive Properties**: 
  - \( c(u + v) = c \cdot u + c \cdot v \) for any scalar \( c \),
  - \( (c + d) \cdot v = c \cdot v + d \cdot v \) for any scalars \( c, d \).
- **Identity Element of Scalar Multiplication**: Multiplying a vector by the scalar 1 gives the vector itself: \( 1 \cdot v = v \).

Let’s see this in practice using Python with PyTorch:
