# 

In [1]:
import numpy as np  
  
# Example: Creating NumPy arrays (which can be used as matrices)  
A = np.array([[1, 2], [3, 4]])  
B = np.array([[5, 6], [7, 8]])  

In [2]:
A

array([[1, 2],
       [3, 4]])

In [3]:
# Matrix Multiplication  
# Using the dot function or @ operator  
C = np.dot(A, B)  
D = A @ B  

In [4]:
D

array([[19, 22],
       [43, 50]])

In [5]:
# Element-wise Multiplication  
E = A * B 

In [6]:
E

array([[ 5, 12],
       [21, 32]])

In [7]:
# Transposing a Matrix  
A_T = np.transpose(A)  
B_T = B.T  # You can also use the .T attribute 

In [8]:
# Matrix Determinant  
det_A = np.linalg.det(A)

In [9]:
det_A

-2.0000000000000004

In [10]:
# Matrix Inverse  
inv_A = np.linalg.inv(A)

In [11]:
inv_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
# Matrix Trace  
trace_A = np.trace(A) 
trace_A

5

In [13]:
# Solving a system of linear equations (Ax = b)  
b = np.array([1, 2])  
x = np.linalg.solve(A, b)  
  
print("\nSolving the system Ax = b for x, where b = [1, 2]:")  
print(x)  


Solving the system Ax = b for x, where b = [1, 2]:
[0.  0.5]


In [14]:
from scipy.linalg import lu
# Define a matrix  
A = np.array([  
    [1, 2, 3],  
    [4, 5, 6],  
    [7, 8, 9]  
])  
  
print("Matrix A:")  
print(A)  

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Compute the rank of the matrix  
rank = np.linalg.matrix_rank(A)  
print("\nRank of Matrix A:")  
print(rank)  


Rank of Matrix A:
2


In [16]:
def rref(A):  
    A = A.astype(float)  # Convert to float for division  
    rows, cols = A.shape  
    r = 0  # row  
    pivots_pos = []  
      
    for c in range(cols):  
        if r >= rows:  
            break  
        # Find the pivot row  
        pivot = np.argmax(np.abs(A[r:rows, c])) + r  
        if A[pivot, c] == 0:  
            continue  
        # Swap the current row with the pivot row  
        A[[r, pivot]] = A[[pivot, r]]  
        pivots_pos.append((r, c))  
        # Normalize the pivot row  
        A[r] = A[r] / A[r, c]  
        # Eliminate the current column  
        for i in range(rows):  
            if i != r:  
                A[i] = A[i] - A[i, c] * A[r]  
        r += 1  
  
    return A, pivots_pos  
  
# Convert the matrix to its RREF  
RREF_A, pivots = rref(A)  
  
print("\nRREF of Matrix A:")  
print(RREF_A)  


RREF of Matrix A:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
