### Introduction to PyTorch: Tensors

PyTorch is a popular open-source machine learning library that provides a flexible and efficient platform for deep learning research and production. At its core, PyTorch leverages a key data structure called **Tensors**, which are similar to NumPy arrays but with additional features that support GPU acceleration, automatic differentiation, and more. This chapter provides an introduction to Tensors in PyTorch, highlighting their operations and usage.

#### What are Tensors?

Tensors can be thought of as generalized matrices. In mathematics, a tensor extends the idea of:
- **Scalars** (0D),
- **Vectors** (1D),
- **Matrices** (2D),
to higher dimensions (3D and beyond).

In PyTorch, Tensors are used to store data that can be manipulated in a variety of ways.

#### Creating Tensors

You can create Tensors in several ways:
- Directly from data.
- From NumPy arrays.
- Using PyTorch’s built-in functions.

Here is how you create a Tensor using PyTorch:



In [5]:
import torch
# Creating a tensor from a list
data = [[1 , 2], [3, 4]]
tensor_from_list = torch . tensor ( data )
# Creating a tensor from a NumPy array
import numpy as np
numpy_array = np. array ( data )
tensor_from_numpy = torch . from_numpy ( numpy_array )
# Creating a tensor using built -in functions
tensor_zeros = torch.zeros ((2 , 2))
tensor_ones = torch.ones ((2 , 2))
tensor_random = torch.rand((2 , 2))
print(tensor_zeros)
print(tensor_ones)
print(tensor_random)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8349, 0.4718],
        [0.6434, 0.2210]])


### Tensor Properties

Tensors have several important properties that are essential to understand when working with PyTorch:

- **Shape**: The dimensions of the tensor, which describe the size in each dimension.
- **Data type**: The data type of the tensor elements, such as `float32`, `int64`, etc.
- **Device**: Tensors can reside on the CPU or GPU, allowing you to leverage hardware acceleration for computations.

Here’s how to check and manipulate these properties in PyTorch:


In [6]:
# Checking tensor properties
tensor = torch . rand ((3 , 3))
# Shape of the tensor
print ( tensor . shape )
# Data type of the tensor
print ( tensor . dtype )
# Device of the tensor
print ( tensor . device )

torch.Size([3, 3])
torch.float32
cpu


### Moving Tensors to GPU

To take advantage of GPU acceleration, you can move tensors to the GPU. PyTorch must be installed with CUDA support to use this feature.

#### Installing PyTorch with CUDA Support

To install PyTorch with CUDA, run the following command in your terminal (for Windows or Linux):

```bash
pip install torch torchvision torchaudio


In [7]:
torch.cuda.is_available()

False

In [8]:
import torch

# Check for CUDA support
if torch.cuda.is_available():
    print("CUDA is available.")
    num_cuda_devices = torch.cuda.device_count()
    for device_id in range(num_cuda_devices):
        print(f"CUDA Device {device_id}: {torch.cuda.get_device_name(device_id)}")
else:
    print("CUDA is not available.")

# Check for MPS (Apple Silicon) support
if torch.backends.mps.is_available():
    print("MPS (Apple Silicon) is available.")
else:
    print("MPS is not available.")

# Default device is CPU, which is always available
print("CPU is available.")


CUDA is not available.
MPS is not available.
CPU is available.


In [9]:
# you can move to colab and try it there if you don;t have a GPU. 

import torch

# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device("cuda")  # Specify device as CUDA (GPU)
    print("CUDA is available. Using GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")  # Fallback to CPU if CUDA is not available
    print("CUDA is not available. Using CPU.")

# Create a tensor on the CPU
cpu_tensor = torch.randn((2, 2))
print("\nTensor on CPU:\n", cpu_tensor)

# Move the tensor to the GPU
gpu_tensor = cpu_tensor.to(device)
print("\nTensor moved to GPU:\n", gpu_tensor)

# Perform a simple operation on the GPU
gpu_result = gpu_tensor * 2
print("\nResult of tensor operation on GPU:\n", gpu_result)

# If needed, move the result back to CPU
cpu_result = gpu_result.to("cpu")
print("\nResult moved back to CPU:\n", cpu_result)


CUDA is not available. Using CPU.

Tensor on CPU:
 tensor([[-0.8339,  0.6388],
        [-1.3498,  1.1626]])

Tensor moved to GPU:
 tensor([[-0.8339,  0.6388],
        [-1.3498,  1.1626]])

Result of tensor operation on GPU:
 tensor([[-1.6677,  1.2775],
        [-2.6995,  2.3252]])

Result moved back to CPU:
 tensor([[-1.6677,  1.2775],
        [-2.6995,  2.3252]])
